name: LegendaryWeaponsSMP
version: '1.0.0'
main: com.alterSMP.legendaryweapons.LegendaryWeaponsPlugin
api-version: '1.21'
description: 'Legendary Weapons SMP with unique items and abilities'
author: AlterSMP
softdepend: [CombatLogger]

commands:
  giveforge:
    description: 'Gives a Legendary Forge to a player'
    usage: '/giveforge [player]'
    permission: legendaryweapons.giveforge
    permission-message: 'You do not have permission to use this command'

  ability:
    description: 'Use legendary weapon abilities'
    usage: '/ability <1|2>'

  kreset:
    description: 'Reset all legendary crafting progress for all players'
    usage: '/kreset'
    permission: legendaryweapons.kreset
    permission-message: 'You do not have permission to use this command'

  kresetplayer:
    description: 'Reset legendary crafting progress for a specific player'
    usage: '/kresetplayer <player>'
    permission: legendaryweapons.kresetplayer
    permission-message: 'You do not have permission to use this command'

  lreload:
    description: 'Reload the plugin configuration'
    usage: '/lreload'
    permission: legendaryweapons.reload
    permission-message: 'You do not have permission to use this command'

  cooldown:
    description: 'Clear all ability cooldowns for yourself or another player'
    usage: '/cooldown [player]'
    permission: legendaryweapons.cooldown
    permission-message: 'You do not have permission to use this command'

  trust:
    description: 'Toggle trust for another player (legendary abilities will not affect them)'
    usage: '/trust <player>'

  givelegendary:
    description: 'Give a legendary weapon for testing (does not mark as crafted)'
    usage: '/givelegendary <legendary_id> [player]'
    permission: legendaryweapons.givelegendary
    permission-message: 'You do not have permission to use this command'

  togglecooldown:
    description: 'Toggle ability cooldown display in action bar'
    usage: '/togglecooldown'

  ldisable:
    description: 'Toggle a legendary weapon crafting availability'
    usage: '/ldisable <legendary_id|list>'
    permission: legendaryweapons.disable
    permission-message: 'You do not have permission to use this command'

  heartreset:
    description: 'Reset heart steal data for a player or all players'
    usage: '/heartreset <player|all>'
    permission: legendaryweapons.admin
    permission-message: 'You do not have permission to use this command'

permissions:
  legendaryweapons.giveforge:
    description: 'Allows giving legendary forges'
    default: op

  legendaryweapons.kreset:
    description: 'Allows resetting legendary crafting progress'
    default: op

  legendaryweapons.kresetplayer:
    description: 'Allows resetting legendary crafting progress for specific players'
    default: op

  legendaryweapons.reload:
    description: 'Allows reloading the plugin configuration'
    default: op

  legendaryweapons.cooldown:
    description: 'Allows clearing ability cooldowns'
    default: op

  legendaryweapons.givelegendary:
    description: 'Allows giving legendary weapons for testing (does not mark as crafted)'
    default: op

  legendaryweapons.disable:
    description: 'Allows disabling/enabling legendary weapons from being crafted'
    default: op

  legendaryweapons.admin:
    description: 'Admin permissions for heart reset and other admin commands'
    default: op
