name: LegendaryWeaponsSMP
version: '1.0.0'
main: com.alterSMP.legendaryweapons.LegendaryWeaponsPlugin
api-version: '1.21'
description: 'Legendary Weapons SMP with unique items and abilities'
author: AlterSMP

commands:
  givealtar:
    description: 'Gives a Legendary Altar to a player'
    usage: '/givealtar [player]'
    permission: legendaryweapons.givealtar
    permission-message: 'You do not have permission to use this command'

  ability:
    description: 'Use legendary weapon abilities'
    usage: '/ability <1|2>'

  kreset:
    description: 'Reset all legendary crafting progress for all players'
    usage: '/kreset'
    permission: legendaryweapons.kreset
    permission-message: 'You do not have permission to use this command'

  kresetplayer:
    description: 'Reset legendary crafting progress for a specific player'
    usage: '/kresetplayer <player>'
    permission: legendaryweapons.kresetplayer
    permission-message: 'You do not have permission to use this command'

  lreload:
    description: 'Reload the plugin configuration'
    usage: '/lreload'
    permission: legendaryweapons.reload
    permission-message: 'You do not have permission to use this command'

  cooldown:
    description: 'Clear all ability cooldowns for yourself or another player'
    usage: '/cooldown [player]'
    permission: legendaryweapons.cooldown
    permission-message: 'You do not have permission to use this command'

  giveweapon:
    description: 'Give a legendary weapon to yourself or another player'
    usage: '/giveweapon <weapon> [player]'
    permission: legendaryweapons.giveweapon
    permission-message: 'You do not have permission to use this command'

  trust:
    description: 'Toggle trust for another player (legendary abilities will not affect them)'
    usage: '/trust <player>'

  givelegendary:
    description: 'Give a legendary weapon for testing (does not mark as crafted)'
    usage: '/givelegendary <legendary_id> [player]'
    permission: legendaryweapons.givelegendary
    permission-message: 'You do not have permission to use this command'

permissions:
  legendaryweapons.givealtar:
    description: 'Allows giving legendary altars'
    default: op

  legendaryweapons.kreset:
    description: 'Allows resetting legendary crafting progress'
    default: op

  legendaryweapons.kresetplayer:
    description: 'Allows resetting legendary crafting progress for specific players'
    default: op

  legendaryweapons.reload:
    description: 'Allows reloading the plugin configuration'
    default: op

  legendaryweapons.cooldown:
    description: 'Allows clearing ability cooldowns'
    default: op

  legendaryweapons.giveweapon:
    description: 'Allows giving legendary weapons'
    default: op

  legendaryweapons.givelegendary:
    description: 'Allows giving legendary weapons for testing (does not mark as crafted)'
    default: op
